name: Can we rerun?

on:
  workflow_dispatch:

jobs:
  quick-random-failing:
    runs-on: ubuntu-latest
    steps:
      - run: exit $(($RANDOM % 2))

  long-running:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 120

  final:
    needs:
      - quick-random-failing
      - long-running
    runs-on: ubuntu-latest
    steps:
      - run: echo success

